### ISSUE TITLE
add a method to get all the players from a country

### ISSUE THREAD

**Issue by pandaro** [beyond-all-reason/data-processing#1]
If possible it would be nice to have a method to get a list of IDs of players that have a certain country.
This could be obtained by inserting the data in players.parquet as "country = countricode".
Or in the replay database by integrating an API that can filter players according to their countrycode.
Thanks for your attention

**Comment by gehuybre** [comment]
I have looked into this a bit further.

**Note:** I assume the country information is stored in a column named `countryCode` in the `teiserver.public.account_users` table, based on the field name found in the public replay API.

#### 1. Add `countryCode` to the Intermediate Player Model

First, put the `countryCode` column in the `tei_players` intermediate model.

**File:** `models/intermediate/tei_players.sql`
```sql
SELECT
  id AS user_id,
  name,
  countryCode
FROM {{ source('pgdumps', 'teiserver_users') }}
```

#### 2. Add `countryCode` to the `players` Mart

Next, add the new column to the final `players.parquet` mart.

**File:** `models/marts/players.sql`
```sql
{{ config(location='data_export/players.parquet') }}

WITH
  active_players AS (
    SELECT DISTINCT user_id
    FROM {{ ref("match_players") }}
  )
SELECT
  user_id,
  name,
  countryCode
FROM active_players
INNER JOIN {{ ref("tei_players") }}
  USING (user_id)
ORDER BY user_id
```

#### 3. Update Schema Documentation

Finally, document the new column in the schema for discoverability.

**File:** `models/marts/schema.yml`
```yaml
# ... (existing content for matches)
  - name: players
    description: List of active players
    columns:
      # ... (existing columns)
      - name: name
        # ...
      - name: countryCode
        description: "Two-letter country code for the user, if available."
```
---

### Important Notes

* **Verification:** The assumption that the column is named `countryCode` is based on API responses. I don't know the exact column name in the production `teiserver.public.account_users` table. The local development data cannot be used for this verification, as `scripts/build_dev_data.sql` intentionally creates a minimal `teiserver_users.parquet` sample that excludes this column.
* **Validation:** I have validated this solution locally by adding dummy `countryCode` data to the dev dataset. The `dbt run` and `dbt test` commands both completed successfully.
